# Site settings
title: Nicolas Hoizey
email: nicolas@hoizey.com
description: > # this means to ignore newlines until "baseurl:"
  Le recueil de créations et réflexions de Nicolas Hoizey
  sur la photo, le Web, etc.
baseurl: ""
url: "https://nicolas-hoizey.com"
twitter_username: nhoizey
github_username:  nhoizey

# Markdown parsing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_backlink: "⬆︎"
  header_offset: 1

# Indexing for related post using the classifier-reborn plugin
lsi: false

# Collections
collections:
  posts:
    output: true
    permalink: :year/:month/:title.html
  notes:
    output: true
    permalink: notes/:year/:month:day:hour:minute:second.html

# Defaults
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      lang: fr
  -
    scope:
      path: ""
      type: notes
    values:
      layout: note
      lang: fr

# Tags
tag_page_layout: tag
tag_page_dir: tags
tag_feed_layout: atom-tag
tag_feed_dir: tags

exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
  - Rakefile
include:
  - .htaccess
  - .well-known
  - favicon.jpg
  - tags

# Pagination (used to mix posts and notes, at least)
pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: '/page-:num.html'
  title: ':title - page :num / :max'
  trail:
    before: 2
    after: 2

# Jekyll Assets
assets:
  compression: false
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 10"

# Algolia
algolia:
  application_id: …
  index_name: …
  read_only_api_key: …
  nodes_to_index: 'p,li,figcaption,blockquote'
  files_to_exclude:
    - 404.html
    - index.html
    - recherche.html
    - offline.html
    - indisponible.html
    - tags/index.html

# Webmention
webmentions:
  username: nicolas-hoizey.com
  cache_folder: _data/webmentions
  cache_bad_uris_for: 5
  pause_lookups: false
  collections:
    - notes
  templates:
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html
  js: false
  legacy_domains:
    - http://nicolas-hoizey.com
  throttle_lookups:
    last_week: daily
    last_month: daily
    last_year: weekly
    older: every 2 weeks

# YouTube
youtube:
  api_key: …

# Cloudinary
cloudinary:
  cloud_name: nho
  verbose: false
  presets:
    default:
      min_width: 360
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always
    onehalf:
      min_width: 180
      max_width: 800
      fallback_max_width: 400
      steps: 5
      sizes: '(min-width: 50rem) 25rem, 45vw'
      figure: always
      attributes:
        class: onehalf
    onethird:
      min_width: 120
      max_width: 560
      fallback_max_width: 300
      steps: 5
      sizes: '(min-width: 50rem) 17rem, 30vw'
      figure: always
      attributes:
        class: onethird right
    onefourth:
      min_width: 100
      max_width: 400
      fallback_max_width: 200
      steps: 5
      sizes: '(min-width: 50rem) 13rem, 23vw'
      figure: always
      attributes:
        class: onefourth right
    logo:
      min_width: 100
      max_width: 400
      fallback_max_width: 200
      steps: 3
      sizes: '(min-width: 55rem) 12.5rem, (min-width: 30rem) 22.5vw, 30vw'
      figure: never
      attributes:
        class: logo

# Archives
jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: archives-year
    month: archives-month
  permalinks:
    year: /:year/
    month: /:year/:month/
