# Site settings
title: Nicolas Hoizey
author: Nicolas Hoizey
email: nicolas@hoizey.com
description: > # this means to ignore newlines until "baseurl:"
  Le recueil de créations et réflexions de Nicolas Hoizey
  sur la photo, le Web, etc.
baseurl: ''
url: 'https://nicolas-hoizey.com'
twitter_username: nhoizey
github_username: nhoizey

# Markdown parsing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  footnote_backlink: '⬆︎'
  header_offset: 1

# Indexing for related post using the classifier-reborn plugin
lsi: false

# Collections
collections:
  posts:
    output: true
    permalink: :year/:month/:title.html
  notes:
    output: true
    permalink: notes/:year/:month:day:hour:minute:second.html

# Defaults
defaults:
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      lang: fr
  - scope:
      path: ''
      type: notes
    values:
      layout: note
      lang: fr

# Tags
tag_page_layout: tag
tag_page_dir: tags
tag_feed_layout: atom-tag
tag_feed_dir: tags

exclude:
  - autoprefixer.yml
  - Gemfile*
  - README.md
  - LICENSE.md
  - tags/*.md
  - Rakefile
include:
  - .htaccess
  - .well-known
  - favicon.jpg
  - tags

# Jekyll Assets
assets:
  compression: false
  autoprefixer:
    browsers:
      - 'last 2 versions'
      - 'IE > 10'

# Get data from Notist
jekyll_get:
  data: talks
  json: 'https://noti.st/nhoizey.json'

# POSSEify plugin settings
posseify:
  twitter:
    max_length: 280
    url_length: 23
    note:
      min_hashtags: 1
      max_hashtags: 5
      template: "@posse_content\n\n@posse_tags\n\n@posse_url"
    post:
      min_hashtags: 3
      max_hashtags: 5
      template: "@posse_title\n\n@posse_tags\n\n@posse_url"

# Algolia
algolia:
  application_id: …
  index_name: …
  read_only_api_key: …
  nodes_to_index: 'p,li,figcaption,blockquote'
  files_to_exclude:
    - 404.html
    - index.html
    - search.html
    - offline.html
    - indisponible.html
    - tags/index.html
    - tools/*
    - notes.html

# Webmention
webmentions:
  username: nicolas-hoizey.com
  cache_folder: _data/webmentions
  cache_bad_uris_for: 5
  pause_lookups: false
  collections:
    - notes
  templates:
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html
  js: false
  legacy_domains:
    - http://nicolas-hoizey.com
  throttle_lookups:
    last_week: daily
    last_month: weekly
    last_year: every 2 weeks
    older: every 2 weeks

# YouTube
youtube:
  api_key: …

# Cloudinary
cloudinary:
  cloud_name: nho
  only_prod: true
  verbose: false
  presets:
    default:
      min_width: 360
      max_width: 1600
      fallback_max_width: 800
      steps: 5
      sizes: '(max-width: 55rem) 90vw, 50rem'
      figure: always
    onehalf:
      min_width: 180
      max_width: 800
      fallback_max_width: 400
      steps: 5
      sizes: '(max-width: 55rem) 45vw, 25rem'
      figure: always
      attributes:
        class: onehalf
    onethird:
      min_width: 120
      max_width: 560
      fallback_max_width: 300
      steps: 5
      sizes: '(max-width: 20rem) 45vw, (max-width: 30rem) 30vw, 16.7rem'
      figure: always
      attributes:
        class: onethird right
    onefourth:
      min_width: 100
      max_width: 400
      fallback_max_width: 200
      steps: 5
      sizes: '(max-width: 20rem) 45vw, (max-width: 30rem) 30vw, (max-width: 55rem) 22.5vw, 12.5rem'
      figure: always
      attributes:
        class: onefourth right
    logo:
      min_width: 100
      max_width: 400
      fallback_max_width: 200
      steps: 5
      sizes: '(max-width: 20rem) 45vw, (max-width: 30rem) 30vw, (max-width: 55rem) 22.5vw, 12.5rem'
      figure: never
      attributes:
        class: logo

# Archives
jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: archives-year
    month: archives-month
  permalinks:
    year: /:year/
    month: /:year/:month/
