# POSSEify plugin settings
posseify:
  twitter:
    max_length: 280
    url_length: 23
    link:
      min_hashtags: 1
      max_hashtags: 5
      template: "&#128279; @posse_content<br>\n@posse_url<br>\n<br>\n@posse_tags"
    post:
      min_hashtags: 3
      max_hashtags: 5
      template: "@posse_title\n\n@posse_url\n\n@posse_tags"

# Algolia
algolia:
  nodes_to_index: "p,li,figcaption,blockquote,th,td"
  files_to_exclude:
    - 404.html
    - index.html
    - search.html
    - offline.html
    - offline-fallback.html
    - about/mentions.html
    - tags/index.html
    - links/index.html
    - tools/*

# Webmention
webmentions:
  # debug: true
  username: nicolas-hoizey.com
  cache_folder: _data/webmentions
  cache_bad_uris_for: 5
  pause_lookups: false
  collections:
    - links
  templates:
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html
  js: false
  legacy_domains:
    - http://nicolas-hoizey.com
  throttle_lookups:
    #   last_week: daily
    last_month: daily
    last_year: weekly
    older: every 2 weeks

# Archives
jekyll-archives:
  enabled:
    - year
    - month
  layouts:
    year: archives-year
    month: archives-month
  permalinks:
    year: /:year/
    month: /:year/:month/
