[build]
    command = "npm run build:netlify"
    publish = "_site"
    functions = "functions"
    functionsSource = "_lambdas"

[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy= "no-referrer-when-downgrade"

[[redirects]]
  from = "/favicon.jpg"
  to = "/.well-known/favicon.jpg"

[[redirects]]
  from = "/favicon.ico"
  to = "/.well-known/favicon.ico"

[[redirects]]
  from = "/robots.txt"
  to = "/.well-known/robots.txt"

[[redirects]]
  from = "/humans.txt"
  to = "/.well-known/humans.txt"
