[build]
  command = "npm run build:netlify"
  publish = "_site"
  functions = "functions"
  functionsSource = "_lambdas"

[[plugins]]
package = "netlify-build-plugin-dareboost"

  [plugins.inputs]
  monitoringIds = "3470,10748,15490,19693"
