name: Check Pull Request
on: [pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run ci-check >> $GITHUB_STEP_SUMMARY
